<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Mpai.Core.csproj" />
    <ProjectReference Include="..\..\..\Repository\Repository\Mpai.Repository.csproj" />
    <ProjectReference Include="..\AOE\Mpai.Cae.Aoe.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\..\\..\\AIF\\V3.0\\src\\AIF.SharedStorage\\AIF.SharedStorage.csproj" />
  </ItemGroup>
</Project>