<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SciHost</AssemblyName>
    <RootNamespace>Mpai.Mas.Sci</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\AIF\V3.0\src\AIF.Controller\AIF.Controller.csproj" />
    <ProjectReference Include="..\..\..\AIF\V3.0\src\AIF.Store\AIF.Store.csproj" />
    <ProjectReference Include="..\..\..\AIMs\Core\Mpai.Core.csproj" />
    <ProjectReference Include="..\Mpai.Mas.Rca\Mpai.Mas.Rca.csproj" />
    <ProjectReference Include="..\..\..\AIMs\CVE\V1.0\VOA\Mpai.Cve.Voa.csproj" />
    <ProjectReference Include="..\..\..\AIMs\CAE3\V1.0\AOA\Mpai.Cae.Aoa.csproj" />
    <ProjectReference Include="..\..\..\AIMs\CAE3\V1.0\AOD\Mpai.Cae.Aod.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\ASR\Mpai.Mmc.Asr.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\TIQ\Mpai.Mmc.Tiq.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\TTS\Mpai.Mmc.Tts.csproj" />
    <ProjectReference Include="..\..\..\AIMs\CVE\V1.0\VOD\Mpai.Cve.Vod.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\SOA\Mpai.Mmc.Soa.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\SOD\Mpai.Mmc.Sod.csproj" />
    <ProjectReference Include="..\..\..\AIMs\MMC\V2.5\TTT\Mpai.Mmc.Ttt.csproj" />
  </ItemGroup>

</Project>
