<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.0" />
    <ProjectReference Include="..\..\..\Core\Mpai.Core.csproj" />
    <ProjectReference Include="..\..\..\MMC\V2.5\SIR\Mpai.Mmc.Sir.csproj" />
  </ItemGroup>
</Project>
